version: '3.9'

services:
  db:
    image: 'postgres:15-alpine'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: property-manager
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5435:5432
volumes:
  postgres_data:
